### ISSUE TITLE
Freezing after right click new file/folder

### ISSUE THREAD

**Issue by sgrover** [titoBouzout/SideBarEnhancements#236] opened 2015-01-06 20:26 UTC
If I right-click on the sidebar and create a folder or file, Sublime then becomes unstable and quickly locks up.  The file/folder IS created, but rarely shows up in the sidebar before Sublime locks up.  Killing the process isn't enough - I have to logout to end all user initiated processes before I can re-use Sublime.

I'm using Sublime 3, on Kubuntu 14.04.  I've seen this behavior with and without saving a project.  I've recently tried out the SidebarFolders package, but this behavior pre-dates using that and continues with it.  Let me know if I can offer anything more to help diagnose this.  (But it is probably just my box configuration...)  Otherwise I appreciate the package greatly!!

**Comment by titoBouzout** [comment] 2015-01-06 20:31
wow..... try disabling "index_files" from ST preferences

**Comment by sgrover** [comment] 2015-01-06 20:37
so far that is helping.  But with indexing turned off I won't be able to use the "goto definition" option, I think.  (still kinda new to Sublime at this level...)  does this suggest the problem is with the indexing routine and not the sidebarenhancement?

**Comment by titoBouzout** [comment] 2015-01-06 20:40
try removing sidebarenhancement and see if still happens with regular ST

**Comment by sgrover** [comment] 2015-01-06 20:52
Hmm.  Can't right/click create file/folder without the sidebarenhancement.  Manually creating files - via sublime or outside sublime work as expected, with  index_files set to true or false.  No freezing.  So something about how the indexing is being initiated?  Or maybe my "folder list" is just tooooooo large?

**Comment by titoBouzout** [comment] 2015-01-06 20:55
Look, do this: Revert your installation, remove everything, add a sane folder, and check if freezes, 
http://www.sublimetext.com/docs/3/revert.html

Then slow start adding things, till you get the problematic thing..

**Comment by sgrover** [comment] 2015-01-06 21:24
Reverted and added only package control and sidebarenhancements.  No freeze.  Added a Laravel folder to the project.  No freezes when creating a folder or file.  I had *just* done a reset an hour ago to resolve an issue with Package Control, and have only installed some pertinent "popular" packages.  I just went through the process again.  After adding each package, I created a blank .md file.  I saw no freezes this time around.  I also tested using a larger folder - I did see a slightly longer response time after adding a new file, but no freeze.  Restarted Sublime - still good.  Added a theme (Seti_UI).  Immediately froze.

I need to logout/in now and see if removing that theme/package clears up the freeze issue.

For completeness, here the list of packages that I have installed and tested this issue with:
 * Alignment.sublime-package
 * BracketHighlighter.sublime-package
 * DocBlockr.sublime-package
 * Emmet.sublime-package
 * GitGutter-Edge.sublime-package
 * Git.sublime-package
 * HTML5.sublime-package
 * HTML Boilerplate.sublime-package
 * jQuery.sublime-package
 * Laravel Blade Highlighter.sublime-package
 * Pretty JSON.sublime-package
 * SideBarEnhancements.sublime-package
 * SilverStripe.sublime-package
 * Trimmer.sublime-package
 * Plus the Seti_UI theme.

**Comment by titoBouzout** [comment] 2015-01-07 02:22
okeii good luck this

**Comment by titoBouzout** [comment] 2015-01-08 19:41
Ok, I'm going to close this as is very likely to be unrelated with the package, feel free to keep commenting but better open a new forum thread describing the issue is you think is productive.

**Closed by titoBouzout** 2015-01-08 19:41 UTC
Labels: maybe invalid

**Comment by sgrover** [comment] 2015-01-08 19:46
Thanks TitoBouzout.  I appreciate the attention on this.  I'm still not 100% clear what is triggering the issue.  But the index_files = false fix solves the problem.  And the goto definition feature isn't overly critical to me.  I'll open a new issue if I ever track this down AND it is related to the sidebarenhancements package.
